In [1]:
#Write a function so that the columns of the output matrix are powers of the inputvector.
#The order of the powers is determined by the increasing boolean argument. Specifically, when
#increasing is False, the i-th output column is the input vector raised element-wise to the power
#of N - i - 1.

In [1]:
import numpy as np

def vander_matrix(ip, n, increasing=False):
    
    if increasing:
        op = np.array([x**i for x in ip for i in range(n)]).reshape(ip.size,n)
    else:
        op = np.array([x**(n-1-i) for x in ip for i in range(n)]).reshape(ip.size,n)
    return op

ip = np.array([1,2,3,4,5])
no_col = 3
op_dec_order = vander_matrix(ip,no_col,False)
op_inc_order = vander_matrix(ip,no_col,True)

print("Decreasing_order:\n\n",op_dec_order,"\n")
print("Increasing order:\n\n",op_inc_order,"\n")

ip = np.array([1,2,4,6,8,10])
no_col = 5
op_dec_order = vander_matrix(ip,no_col,False)
op_inc_order = vander_matrix(ip,no_col,True)


print("Decreasing_order:\n\n",op_dec_order,"\n")
print("Increasing_order:\n\n",op_inc_order,"\n")



Decreasing_order:

 [[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [16  4  1]
 [25  5  1]] 

Increasing order:

 [[ 1  1  1]
 [ 1  2  4]
 [ 1  3  9]
 [ 1  4 16]
 [ 1  5 25]] 

Decreasing_order:

 [[    1     1     1     1     1]
 [   16     8     4     2     1]
 [  256    64    16     4     1]
 [ 1296   216    36     6     1]
 [ 4096   512    64     8     1]
 [10000  1000   100    10     1]] 

Increasing_order:

 [[    1     1     1     1     1]
 [    1     2     4     8    16]
 [    1     4    16    64   256]
 [    1     6    36   216  1296]
 [    1     8    64   512  4096]
 [    1    10   100  1000 10000]] 



In [3]:
#Write a function to find moving average in an array over a window:
#Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [6]:
def mov_avg_val(mylist, N):
    cumsum, moving_aves = [0], []
    for i, x in enumerate(mylist, 1):
        cumsum.append(cumsum[i-1] + x) 
        if i>=N:
            moving_ave = round(((cumsum[i] - cumsum[i-N])/N),2) 
            moving_aves.append(moving_ave) # listing the moving average as an single array
    print("Moving_average_values: ", moving_aves)

In [7]:
mylist = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
N = 3
mov_avg_val(mylist,N)

Moving_average_values:  [5.0, 4.67, 5.67, 6.67, 9.67, 28.67, 49.33, 72.67, 84.0, 93.33, 116.33]
